[REVIEW] CPU Dask-SQL q02 and q04
rapidsai/gpu-bdb pull request #253
Opened 2022-04-12 16:41 UTC by DaceT

2022-04-25 18:26 UTC, VibhuJawa requested changes
Have requested a small change, looks good otherwise.

2022-04-25 18:26 UTC, VibhuJawa commented on gpu_bdb/bdb_tools/q04_utils.py
> +        .str.cat(filtered_df["wp_type_codes"].astype(str), sep=":")
I suggesting using `string` to follow the recommended practice according to pandas docs https://pandas.pydata.org/pandas-docs/stable/user_guide/text.html . 

```suggestion
        .astype("string")
        .str.cat(filtered_df["wp_type_codes"].astype("string"), sep=":")
```

2022-05-04 19:16 UTC, ChrisJar commented
Can confirm both 2 and 4 return the correct results with GPU and CPU so this is ready for another round of reviews

2022-05-05 19:32 UTC, VibhuJawa approved these changes

2022-05-05 19:34 UTC, VibhuJawa approved these changes

2022-05-05 19:34 UTC, merged